language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 local_dir: dist
 on:
   branch: master
addons:
  ssh_known_hosts:
  - bitbucket.org
  - 18.205.93.1 
