/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XAppBar: typeof import('./src/components/atoms/x-app-bar/x-app-bar.vue')['default']
    XAvatar: typeof import('./src/components/atoms/x-avatar/x-avatar.vue')['default']
    XBottomSheet: typeof import('./src/components/atoms/x-bottom-sheet/x-bottom-sheet.vue')['default']
    XBtn: typeof import('./src/components/atoms/x-btn/x-btn.vue')['default']
    XCard: typeof import('./src/components/atoms/x-card/x-card.vue')['default']
    XCheckbox: typeof import('./src/components/atoms/x-checkbox/x-checkbox.vue')['default']
    XChip: typeof import('./src/components/atoms/x-chip/x-chip.vue')['default']
    XDialog: typeof import('./src/components/atoms/x-dialog/x-dialog.vue')['default']
    XDivider: typeof import('./src/components/atoms/x-divider/x-divider.vue')['default']
    XFooter: typeof import('./src/components/atoms/x-footer/x-footer.vue')['default']
    XIcon: typeof import('./src/components/atoms/x-icon/x-icon.vue')['default']
    XList: typeof import('./src/components/atoms/x-list/x-list.vue')['default']
    XListItem: typeof import('./src/components/atoms/x-list-item/x-list-item.vue')['default']
    XMain: typeof import('./src/components/atoms/x-main/x-main.vue')['default']
    XMenu: typeof import('./src/components/atoms/x-menu/x-menu.vue')['default']
    XNavigationDrawer: typeof import('./src/components/atoms/x-navigation-drawer/x-navigation-drawer.vue')['default']
    XSelect: typeof import('./src/components/atoms/x-select/x-select.vue')['default']
    XSwitch: typeof import('./src/components/atoms/x-switch/x-switch.vue')['default']
    XSystemBar: typeof import('./src/components/atoms/x-system-bar/x-system-bar.vue')['default']
    XTable: typeof import('./src/components/atoms/x-table/x-table.vue')['default']
    XTextField: typeof import('./src/components/atoms/x-text-field/x-text-field.vue')['default']
  }
}
