onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@fortawesome/fontawesome-pro'
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - esbuild
  - yorkie

overrides:
  axios@<0.21.1: '>=0.21.1'
  axios@<0.21.2: '>=0.21.2'
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  braces@<2.3.1: '>=2.3.1'
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@<6.0.6: '>=6.0.6'
  follow-redirects@<1.14.7: '>=1.14.7'
  follow-redirects@<1.14.8: '>=1.14.8'
  follow-redirects@<1.15.4: '>=1.15.4'
  follow-redirects@<=1.15.5: '>=1.15.6'
  form-data@<2.5.4: '>=2.5.4'
  got@<11.8.5: '>=11.8.5'
  http-cache-semantics@<4.1.1: '>=4.1.1'
  http-proxy-middleware@<2.0.7: '>=2.0.7'
  micromatch@<4.0.8: '>=4.0.8'
  node-forge@<1.0.0: '>=1.0.0'
  node-forge@<1.3.0: '>=1.3.0'
  node-forge@<1.3.2: '>=1.3.2'
  node-notifier@<8.0.1: '>=8.0.1'
  postcss@<8.4.31: '>=8.4.31'
  property-expr@<2.0.3: '>=2.0.3'
  qs@<6.14.1: '>=6.14.1'
  simple-git@<3.15.0: '>=3.15.0'
  simple-git@<3.16.0: '>=3.16.0'
  simple-git@<3.3.0: '>=3.3.0'
  simple-git@<3.5.0: '>=3.5.0'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  vue@>=2.0.0-alpha.1 <3.0.0-alpha.0: '>=3.0.0-alpha.0'
  webpack-dev-middleware@<=5.3.3: '>=5.3.4'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
